<a href="https://colab.research.google.com/github/Divanshu-Bansal/Random-Forest-Projects/blob/master/Random_Forest_Classifier_Holiday_Package_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
%matplotlib inline

In [2]:
!git clone https://github.com/Divanshu-Bansal/Random-Forest-Classification-Holiday-package-purchase-prediction.git

Cloning into 'Random-Forest-Classification-Holiday-package-purchase-prediction'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (7/7), 76.34 KiB | 3.18 MiB/s, done.

In [5]:
%cd Random-Forest-Classification-Holiday-package-purchase-prediction/

/content/Random-Forest-Classification-Holiday-package-purchase-prediction

In [6]:
!ls

Dataset  README.md

In [8]:
df = pd.read_csv("Dataset/Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [12]:
df.shape

(4888, 20)

# Data Cleaning

1. Handling Missing Values
2. Handling Duplicates
3. Check Data Types
4. Understand the data

In [16]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [13]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [14]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [15]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [17]:
df['Gender']=df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus']=df['MaritalStatus'].replace('Single', 'Unmarried')

In [18]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [19]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [21]:
## Check Missing Values
features_with_nan = [features for features in df.columns if df[features].isnull().sum()>=1]
for feature in features_with_nan:
  print(feature, np.round(df[feature].isnull().mean()*100,5),"% missing values")

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [23]:
df[features_with_nan].select_dtypes(exclude="object").describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [26]:
## Imputing the null values with Median (Int/ float values) and Mode for (Categorical values)

df.Age.fillna(df.Age.median(), inplace = True)

df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)

df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)

df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace=True)

df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace=True)

df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace=True)

df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace=True)

df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace=True)

/tmp/ipykernel_9055/1081914089.py:9: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_9055/1081914089.py:11: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_9055/1081914089.py:13: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_9055/1081914089.py:15: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_9055/1081914089.py:17: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [27]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

# Feature Engineering

## Feature Extraction

In [28]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [29]:
## Combine number of person visiting and number of children visiting

df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'], axis=1, inplace=True)

In [32]:
## Get all numeric features

num_features = [features for features in df.columns if df[features].dtype != 'O']
print("Number of numerical features:", len(num_features))

Number of numerical features: 13

In [33]:
## Get all Categorical features

cat_features = [features for features in df.columns if df[features].dtype == 'O']
print("Number of categorical features:", len(cat_features))

Number of categorical features: 6

In [35]:
## Discrete Features

discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of discrete features:", len(discrete_features))

Number of discrete features: 9

In [36]:
## Continuous Features

continuous_features = [feature for feature in num_features if feature not in discrete_features]
print("Number of continuous features:", len(continuous_features))

Number of continuous features: 4

In [37]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [38]:
## Independent and Dependent Features

X = df.drop(['ProdTaken'], axis = 1)
y = df['ProdTaken']

In [42]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [43]:
## Train Test Split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape,X_test.shape

((3910, 18), (978, 18))

## One Hot Encoder and Standard Scaling

In [44]:
cat_features = X.select_dtypes(include="object").columns
num_features = X.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [45]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['CustomerID', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [46]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

## Random Forest Classifier Training

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [58]:
## Model training

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train, y_train)

  # Make Predictions
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  # Training Set Performance
  model_train_accuracy = accuracy_score(y_train,y_train_pred)
  model_train_f1 = f1_score(y_train,y_train_pred, average = 'weighted')
  model_train_precision = precision_score(y_train,y_train_pred)
  model_train_recall = recall_score(y_train,y_train_pred)
  model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

  # Test Set Performance
  model_test_accuracy = accuracy_score(y_test,y_test_pred)
  model_test_f1 = f1_score(y_test,y_test_pred, average = 'weighted')
  model_test_precision = precision_score(y_test,y_test_pred)
  model_test_recall = recall_score(y_test,y_test_pred)
  model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


  print(list(models.keys())[i])
  print("-"*15)

  print("Model Performance for Training Set")
  print(" - Accuracy: {:.4f}".format(model_train_accuracy))
  print(" - F1 Score: {:.4f}".format(model_train_f1))
  print(" - Precision: {:.4f}".format(model_train_precision))
  print(" - Recall: {:.4f}".format(model_train_recall))
  print(" - Roc Auc Score: {:.4f}".format(model_train_rocauc_score))

  print('_ '*35)

  print("Model Performance for Test Set")
  print(" - Accuracy: {:.4f}".format(model_test_accuracy))
  print(" - F1 Score: {:.4f}".format(model_test_f1))
  print(" - Precision: {:.4f}".format(model_test_precision))
  print(" - Recall: {:.4f}".format(model_test_recall))
  print(" - Roc Auc Score: {:.4f}".format(model_test_rocauc_score))

  print('= '*35)
  print("\n")

Logistic Regression
---------------
Model Performance for Training Set
 - Accuracy: 0.8468
 - F1 Score: 0.8214
 - Precision: 0.7044
 - Recall: 0.3073
 - Roc Auc Score: 0.6389
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Accuracy: 0.8354
 - F1 Score: 0.8086
 - Precision: 0.6786
 - Recall: 0.2984
 - Roc Auc Score: 0.6321
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Decision Tree
---------------
Model Performance for Training Set
 - Accuracy: 1.0000
 - F1 Score: 1.0000
 - Precision: 1.0000
 - Recall: 1.0000
 - Roc Auc Score: 1.0000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Accuracy: 0.9110
 - F1 Score: 0.9090
 - Precision: 0.8059
 - Recall: 0.7173
 - Roc Auc Score: 0.8377
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Random Forest
---------------
Model Performance for Training Set
 - Accuracy: 1.0000
 - F1 Score: 1.0000
 - Precision: 1.0000
 - Recall: 1.0000
 - Roc Auc Score: 1.0000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Accuracy: 0.9131
 - F1 Score: 0.9044
 - Precision: 0.9569
 - Recall: 0.5812
 - Roc Auc Score: 0.7874
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

## Hyperparameter Tuning

In [59]:
rf_params = {
    "max_depth": [5,8,15,None,10],
    "max_features": [5,7,"auto",8],
    "min_samples_split": [2,8,15,20],
    "n_estimators": [100,200,500,1000]
}

In [60]:
## Models list for hyperparameter tuning

randomcv_models = [
    ("RF", RandomForestClassifier(), rf_params),
]

In [63]:
from sklearn.model_selection import RandomizedSearchCV

model_params = {}
for name, model, params in randomcv_models:
  random = RandomizedSearchCV(estimator = model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)

  random.fit(X_train,y_train)
  model_params[name] = random.best_params_

for model_name in model_params:
  print(f"-------------------------Best Params for {model_name} ---------------------")
  print(model_params[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:


84 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
84 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.


/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning:

One or more of the test scores are non-finite: [0.86930977        nan 0.86752001        nan        nan 0.87416957
 0.853199   0.86649673 0.87519226        nan        nan 0.89667544
 0.89923266 0.85064041 0.87058907 0.8519201  0.87110051 0.87084391
        nan 0.84450211 0.86675314 0.85447791 0.87749385 0.87135535
 0.87851752 0.84424629        nan        nan        nan 0.86547542
 0.86572986        nan 0.87391375        nan        nan 0.86854251
        nan 0.87468101 0.87672737 0.86470678        nan 0.87800608
 0.86726419 0.86496221 0.85243174        nan 0.87161097 0.89820977
 0.89820957 0.87979702 0.87237981 0.86879813        nan 0.8659849
        nan 0.86573045        nan 0.86112746 0.88491165 0.88618898
 0.85166448        nan        nan 0.87340211 0.86445096 0.85294318
 0.85166448        nan 0.88235325 0.89846441 0.86010418 0.88670141
 0.86547424        nan 0.8695652  0.84578121        nan        nan
 0.87314668 0.85217514 0.88235325        nan 0.84475793 0.87033325
        nan 0.87289066 0.89514091 0.86879774 0.88081892 0.8603598
 0.85089682 0.88516688 0.86394089 0.86445076 0.87544768        nan
 0.89897625        nan 0.86572947 0.84654847]

-------------------------Best Params for RF ---------------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 7, 'max_depth': None}

In [64]:
## Model training with Best Parameters

models = {
    "Random Forest": RandomForestClassifier(n_estimators=100, min_samples_split=2, max_features= 7, max_depth= None)
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train, y_train)

  # Make Predictions
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  # Training Set Performance
  model_train_accuracy = accuracy_score(y_train,y_train_pred)
  model_train_f1 = f1_score(y_train,y_train_pred, average = 'weighted')
  model_train_precision = precision_score(y_train,y_train_pred)
  model_train_recall = recall_score(y_train,y_train_pred)
  model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

  # Test Set Performance
  model_test_accuracy = accuracy_score(y_test,y_test_pred)
  model_test_f1 = f1_score(y_test,y_test_pred, average = 'weighted')
  model_test_precision = precision_score(y_test,y_test_pred)
  model_test_recall = recall_score(y_test,y_test_pred)
  model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


  print(list(models.keys())[i])
  print("-"*15)

  print("Model Performance for Training Set")
  print(" - Accuracy: {:.4f}".format(model_train_accuracy))
  print(" - F1 Score: {:.4f}".format(model_train_f1))
  print(" - Precision: {:.4f}".format(model_train_precision))
  print(" - Recall: {:.4f}".format(model_train_recall))
  print(" - Roc Auc Score: {:.4f}".format(model_train_rocauc_score))

  print('_ '*35)

  print("Model Performance for Test Set")
  print(" - Accuracy: {:.4f}".format(model_test_accuracy))
  print(" - F1 Score: {:.4f}".format(model_test_f1))
  print(" - Precision: {:.4f}".format(model_test_precision))
  print(" - Recall: {:.4f}".format(model_test_recall))
  print(" - Roc Auc Score: {:.4f}".format(model_test_rocauc_score))

  print('= '*35)
  print("\n")

Random Forest
---------------
Model Performance for Training Set
 - Accuracy: 1.0000
 - F1 Score: 1.0000
 - Precision: 1.0000
 - Recall: 1.0000
 - Roc Auc Score: 1.0000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Accuracy: 0.9243
 - F1 Score: 0.9187
 - Precision: 0.9466
 - Recall: 0.6492
 - Roc Auc Score: 0.8202
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =