<a href="https://colab.research.google.com/github/Divanshu-Bansal/Random-Forest-Projects/blob/master/Random_forest_Regressor_Used_Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
%matplotlib inline

In [2]:
!git clone https://github.com/Divanshu-Bansal/Random-Forest-Projects.git

Cloning into 'Random-Forest-Projects'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 1), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 315.97 KiB | 9.57 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [3]:
%cd Random-Forest-Projects/

/content/Random-Forest-Projects

In [4]:
df = pd.read_csv("Dataset/cardekho_imputated.csv",index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

# Data Cleaning

1. Handling Missing Values
2. Handling Duplicates
3. Check Data Types
4. Understand the data

In [5]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
df.drop(['car_name', 'brand'], axis=1, inplace=True)

In [7]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [8]:
## Get all numeric features
num_features = [features for features in df.columns if df[features].dtype != 'O']
print("Number of numerical features:", len(num_features))


## Get all Categorical features
cat_features = [features for features in df.columns if df[features].dtype == 'O']
print("Number of categorical features:", len(cat_features))


## Discrete Features
discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of discrete features:", len(discrete_features))


## Continuous Features
continuous_features = [feature for feature in num_features if feature not in discrete_features]
print("Number of continuous features:", len(continuous_features))

Number of numerical features: 7
Number of categorical features: 4
Number of discrete features: 2
Number of continuous features: 5

In [9]:
## Independent and Dependent Features

from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'],axis=1)
y = df['selling_price']

In [10]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Train and Test Split

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30, random_state=42)

## Encoding the features

In [12]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [13]:
len(df['model'].unique())

120

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le1 = LabelEncoder()
X_train['model']=le1.fit_transform(X_train['model'])
X_test['model']=le1.fit_transform(X_test['model'])

In [16]:
X_train.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
8218,71,4,41000,Dealer,Diesel,Manual,20.14,1498,88.70,5
13969,116,7,120000,Individual,Diesel,Manual,22.54,1396,88.73,5
16328,31,8,110000,Individual,Diesel,Manual,19.87,1461,83.80,5
11684,86,5,60000,Individual,Petrol,Manual,20.40,1197,83.11,5
7453,95,5,28000,Dealer,Petrol,Manual,17.01,1591,121.30,5

In [17]:
len(df['seller_type'].unique()), len(df['fuel_type'].unique()), len(df['transmission_type'].unique())

(3, 5, 2)

The number of unique features are less so we can do OneHotEncoding for the above three categorical features.

In [18]:
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']


from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop="first")

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)
    ],
    remainder='passthrough'
)

In [19]:
X_train = preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [20]:
X_train[0]

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -6.76544573e-01,
       -3.43637741e-01,  8.95912446e-02,  3.18221558e-02, -2.70404276e-01,
       -4.01881283e-01,  7.10000000e+01])

## Model Training and Model Selection

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [22]:
## Function to evaluate a Model

def evaluate_model(true, predicted):
  mae = mean_absolute_error(true, predicted)
  mse = mean_squared_error(true, predicted)
  rmse = np.sqrt(mse)
  r2 = r2_score(true,predicted)
  return mae,mse,rmse,r2

In [56]:
# Model Training
## Model training

models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbour Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor()
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train, y_train)

  # Make Predictions
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  # Evaluate Train and Test Datatset
  model_train_mae,model_train_mse,model_train_rmse,model_train_r2_score = evaluate_model(y_train,y_train_pred)
  model_test_mae,model_test_mse,model_test_rmse,model_test_r2_score = evaluate_model(y_test,y_test_pred)


  print(list(models.keys())[i])
  print("-"*15)

  print("Model Performance for Training Set")
  print(" - Mean Absolute Error: {:.4f}".format(model_train_mae))
  print(" - Mean Squared Error: {:.4f}".format(model_train_mse))
  print(" - Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print(" - R2 Score: {:.4f}".format(model_train_r2_score))

  print('_ '*35)

  print("Model Performance for Test Set")
  print(" - Mean Absolute Error: {:.4f}".format(model_test_mae))
  print(" - Mean Squared Error: {:.4f}".format(model_test_mse))
  print(" - Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print(" - R2 Score: {:.4f}".format(model_test_r2_score))

  print('= '*35)
  print("\n")

Linear Regression
---------------
Model Performance for Training Set
 - Mean Absolute Error: 268413.1905
 - Mean Squared Error: 312851226135.4937
 - Root Mean Squared Error: 559331.0524
 - R2 Score: 0.6183
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 281155.3500
 - Mean Squared Error: 257425563356.9935
 - Root Mean Squared Error: 507371.2283
 - R2 Score: 0.6577
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Lasso
---------------
Model Performance for Training Set
 - Mean Absolute Error: 268412.2485
 - Mean Squared Error: 312851237706.5615
 - Root Mean Squared Error: 559331.0627
 - R2 Score: 0.6183
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 281154.9472
 - Mean Squared Error: 257424777514.2888
 - Root Mean Squared Error: 507370.4539
 - R2 Score: 0.6577
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Ridge
---------------
Model Performance for Training Set
 - Mean Absolute Error: 268369.4188
 - Mean Squared Error: 312852141688.1268
 - Root Mean Squared Error: 559331.8708
 - R2 Score: 0.6183
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 281104.5752
 - Mean Squared Error: 257408893453.6246
 - Root Mean Squared Error: 507354.8004
 - R2 Score: 0.6577
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


K-Neighbour Regressor
---------------
Model Performance for Training Set
 - Mean Absolute Error: 88155.7430
 - Mean Squared Error: 99666131921.7577
 - Root Mean Squared Error: 315699.4329
 - R2 Score: 0.8784
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 513600.2000
 - Mean Squared Error: 1025765115965.7494
 - Root Mean Squared Error: 1012800.6299
 - R2 Score: -0.3639
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Decision Tree
---------------
Model Performance for Training Set
 - Mean Absolute Error: 4728.8897
 - Mean Squared Error: 413298475.0162
 - Root Mean Squared Error: 20329.7436
 - R2 Score: 0.9995
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 159315.8142
 - Mean Squared Error: 182481283311.6019
 - Root Mean Squared Error: 427178.2805
 - R2 Score: 0.7574
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Random Forest Regressor
---------------
Model Performance for Training Set
 - Mean Absolute Error: 39931.2119
 - Mean Squared Error: 17375095395.6077
 - Root Mean Squared Error: 131814.6251
 - R2 Score: 0.9788
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 127957.2654
 - Mean Squared Error: 81350515805.2623
 - Root Mean Squared Error: 285220.1182
 - R2 Score: 0.8918
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

## Hyperparameter Tuning

In [57]:
rf_params = {
    "max_depth": [5,8,15,None,10],
    "max_features": [5,7,"auto",8],
    "min_samples_split": [2,8,15,20],
    "n_estimators": [100,200,500,1000]
}

In [58]:
randomcv_models = [
    ('RF', RandomForestRegressor(), rf_params)
]

In [59]:
from sklearn.model_selection import RandomizedSearchCV

model_params = {}
for name, model, params in randomcv_models:
  random = RandomizedSearchCV(estimator = model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)

  random.fit(X_train,y_train)
  model_params[name] = random.best_params_

for model_name in model_params:
  print(f"-------------------------Best Params for {model_name} ---------------------")
  print(model_params[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits

/usr/local/lib/python3.13/dist-packages/joblib/externals/loky/process_executor.py:787: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
84 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
58 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.79055311 0.84318422 0.76936485 0.84886482 0.82429696 0.83739804
 0.85082829 0.84160531 0.83844246 0.83166699 0.84069913 0.8514778
 0.84223793 0.80738637        nan        nan 0.77924019        nan
 0.7863084  0.85036977 0.82485962        nan        nan 0.84288304
 0.84353207        nan 0.79760835 0.83339109 0.85548749 0.85982185
 0.85444286 0.82945431 0.85187173 0.83878421 0.81328089        nan
        nan 0.84538181 0.82259894 0.84347639 0.83966762 0.8174157
 0.80114968        nan 0.83309351        nan        nan 0.83151687
        nan 0.81852079 0.83311956 0.79898666 0.85512272 0.80056951
 0.85916563        nan 0.83898727 0.78777014 0.84105142        nan
 0.82660746        nan        nan        nan        nan 0.84452649
 0.84587131 0.80373979 0.85891344        nan 0.84137146        nan
        nan 0.85055054        nan 0.84008365 0.83563505        nan
 0.83622604 0.85849042 0.78966563 0.80166691 0.84036995 0.83804967
 0.85796612 0.84840667        nan 0.84691633 0.82573216 0.86203397
        nan 0.84108338 0.77697866 0.79954397 0.86234296 0.85113087
 0.84650133        nan        nan        nan]
  warnings.warn(

-------------------------Best Params for RF ---------------------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}

In [23]:
## Model training with Best Parameters

models = {
    "Random Forest": RandomForestRegressor(n_estimators=1000, min_samples_split=2, max_features= 8, max_depth= None)
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train, y_train)

  # Make Predictions
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)


  # Evaluate Train and Test Datatset
  model_train_mae,model_train_mse,model_train_rmse,model_train_r2_score = evaluate_model(y_train,y_train_pred)
  model_test_mae,model_test_mse,model_test_rmse,model_test_r2_score = evaluate_model(y_test,y_test_pred)


  print(list(models.keys())[i])
  print("-"*15)

  print("Model Performance for Training Set")
  print(" - Mean Absolute Error: {:.4f}".format(model_train_mae))
  print(" - Mean Squared Error: {:.4f}".format(model_train_mse))
  print(" - Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print(" - R2 Score: {:.4f}".format(model_train_r2_score))

  print('_ '*35)

  print("Model Performance for Test Set")
  print(" - Mean Absolute Error: {:.4f}".format(model_test_mae))
  print(" - Mean Squared Error: {:.4f}".format(model_test_mse))
  print(" - Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print(" - R2 Score: {:.4f}".format(model_test_r2_score))

  print('= '*35)
  print("\n")

  # # Training Set Performance
  # model_train_accuracy = accuracy_score(y_train,y_train_pred)
  # model_train_f1 = f1_score(y_train,y_train_pred, average = 'weighted')
  # model_train_precision = precision_score(y_train,y_train_pred)
  # model_train_recall = recall_score(y_train,y_train_pred)
  # model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

  # # Test Set Performance
  # model_test_accuracy = accuracy_score(y_test,y_test_pred)
  # model_test_f1 = f1_score(y_test,y_test_pred, average = 'weighted')
  # model_test_precision = precision_score(y_test,y_test_pred)
  # model_test_recall = recall_score(y_test,y_test_pred)
  # model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


  # print(list(models.keys())[i])
  # print("-"*15)

  # print("Model Performance for Training Set")
  # print(" - Accuracy: {:.4f}".format(model_train_accuracy))
  # print(" - F1 Score: {:.4f}".format(model_train_f1))
  # print(" - Precision: {:.4f}".format(model_train_precision))
  # print(" - Recall: {:.4f}".format(model_train_recall))
  # print(" - Roc Auc Score: {:.4f}".format(model_train_rocauc_score))

  # print('_ '*35)

  # print("Model Performance for Test Set")
  # print(" - Accuracy: {:.4f}".format(model_test_accuracy))
  # print(" - F1 Score: {:.4f}".format(model_test_f1))
  # print(" - Precision: {:.4f}".format(model_test_precision))
  # print(" - Recall: {:.4f}".format(model_test_recall))
  # print(" - Roc Auc Score: {:.4f}".format(model_test_rocauc_score))

  # print('= '*35)
  # print("\n")

Random Forest
---------------
Model Performance for Training Set
 - Mean Absolute Error: 38901.7646
 - Mean Squared Error: 17278924420.3934
 - Root Mean Squared Error: 131449.3226
 - R2 Score: 0.9789
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Model Performance for Test Set
 - Mean Absolute Error: 110499.1936
 - Mean Squared Error: 59330836626.7921
 - Root Mean Squared Error: 243579.2204
 - R2 Score: 0.9211
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =